apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
namePrefix: staging-
images:
- name: BACKEND/IMAGE
  newName: gcr.io/dwk-gke-416915/backend
  newTag: develop-2e2f7985be77cddeb0a6d91b66b11901dddaae63
- name: gcr.io/dwk-gke-416915/backend
  newName: gcr.io/dwk-gke-416915/backend
  newTag: develop-4219e2444c6aee0a6885e88480b4c8f536d7e9ee
