apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
namePrefix: staging-
images:
- name: BACKEND/IMAGE
  newName: gcr.io/dwk-gke-416915/backend
- name: gcr.io/dwk-gke-416915/backend
  newName: gcr.io/dwk-gke-416915/backend
  newTag: develop-0b70672373bfc094df57da80686440ae6a0b9765
