apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
namePrefix: staging-
images:
- name: BACKEND/IMAGE
  newName: gcr.io/dwk-gke-416915/backend
  newTag: develop-2e2f7985be77cddeb0a6d91b66b11901dddaae63
- name: gcr.io/dwk-gke-416915/backend
  newName: gcr.io/dwk-gke-416915/backend
  newTag: develop-28a20bc6b2d9bb8e1976479369125c6f211080c5
