apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
namePrefix: staging-
images:
- name: BACKEND/IMAGE
  newName: gcr.io/dwk-gke-416915/backend
  newTag: develop-b220e6503586a48686c7d9c505164a85a74044ca
- name: gcr.io/dwk-gke-416915/backend
  newName: gcr.io/dwk-gke-416915/backend
  newTag: develop-8efd7b546f9574de800fd08bdd3af1be511bb0ca
