apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
images:
- name: BACKEND/IMAGE
  newName: gcr.io/dwk-gke-416915/backend
  newTag: develop-ee5e39c7aa068c44b2905a66055a48b18f80aed6

