apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  -  ./../base
  - postgres-secrets.yaml
  - database-config.yaml
  - statefulset.yaml
  - rollout-deployment.yaml
  - ingress.yaml
  - nats-config.yaml
namePrefix: staging-
images:
  - name: BACKEND/IMAGE
    newName: gcr.io/dwk-gke-416915/backend