apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: cpu-usage-develop
spec:
  metrics:
    - name: cpu-usage-develop
      initialDelay: 1m
      interval: 1m
      count: 1
      successCondition: result < 1.5
      failureCondition: result >= 1.5
      provider:
        prometheus:
          address: http://kube-prometheus-stack-prometheus.prometheus.svc.cluster.local:9090
          query: |
            scalar(
            sum(rate(container_cpu_usage_seconds_total{namespace="develop"}[1m]))
            )

        
