apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - rollout-deployment.yaml
  - statefulset.yaml
  - postgres-secrets.yaml
  - database-config.yaml
  - nats-config.yaml
  - ingress.yaml
  - analysistemplate.yaml

