name: Deploy to Develop

on:
  push:
    branches:
      - develop

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: dwk-cluster
  GKE_ZONE: europe-north1-b
  IMAGE: backend

jobs:
  build-publish-deploy:
    name: Build, Publish and Deployment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Checkout application repository
        uses: actions/checkout@v3
        with:
          repository: lapalmerjack/kubernetes-project-backend  # Replace with your repository name
          path: app-source
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: 'latest'
          project_id: ${{ secrets.GKE_PROJECT }}

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GKE_SA_KEY }}

      - run: gcloud --quiet auth configure-docker

      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}

      - name: Build
        run: |-
          docker build \
            --tag "gcr.io/$PROJECT_ID/$IMAGE:${GITHUB_REF#refs/heads/}-$GITHUB_SHA" \
            ./app-source

      - name: Publish
        run: |
          docker push "gcr.io/$PROJECT_ID/$IMAGE:${GITHUB_REF#refs/heads/}-$GITHUB_SHA"

      - name: Set up Kustomize
        run: |-
          curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
          chmod u+x ./kustomize
          sudo mv ./kustomize /usr/local/bin/kustomize

      - name: Update Kustomize Image Manually
        run: |-
          cd overlays/staging
          sed -i "s|newTag: .*|newTag: ${GITHUB_REF#refs/heads/}-${GITHUB_SHA}|g" kustomization.yaml

      - name: Verify kustomization.yaml
        run: |
          cat overlays/staging/kustomization.yaml

      - name: Commit kustomization.yaml to GitHub
        uses: EndBug/add-and-commit@v9
        with:
          cwd: overlays/staging
          add: "kustomization.yaml"
          message: New version released ${{ github.sha }}
